### ISSUE TITLE
I encountered a crash when installing essentiapipes-1.7.10-v1.1.2.jar to the server

### ISSUE THREAD

**Issue by mcmso** [rndmorris/Essentia-Pipes#12]
https://paste.ubuntu.com/p/CQg6kRnXg8/
But in sp, it runs everything fine

**Comment by rndmorris** [comment]
I didn't have any luck reproducing this on my end, but I believe the issue should be resolved in the latest patch. Could you download 
`essentiapipes-1.7.10-v1.1.3.jar` from the latest release (found here: https://github.com/rndmorris/Essentia-Pipes/releases/tag/1.7.10-v1.1.3) and let me know if that fixes the crash?

**Comment by mcmso** [comment]
Fixed it. Thanks a lot
